# =============================================
# SQL Anywhere \u2014 BD vieja (solo lectura)
# =============================================
sybase.datasource.url=jdbc:sybase:Tds:190.128.241.46:49152/yml_dutriec
sybase.datasource.username=TU_USUARIO
sybase.datasource.password=TU_CONTRASE\u00d1A
sybase.datasource.driver-class-name=com.sybase.jdbc3.jdbc.SybDriver
sybase.datasource.hikari.connection-test-query=SELECT 1

# =============================================
# MariaDB \u2014 BD local (trazabilidad)
# =============================================
mariadb.datasource.url=jdbc:mariadb://localhost:3306/retenciones_sifen
mariadb.datasource.username=root
mariadb.datasource.password=TU_CONTRASE\u00d1A_MARIADB
mariadb.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =============================================
# Servidor
# =============================================
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
spring.web.resources.static-locations=classpath:/static/